models:
  - name: "SimpleModel"
    versions:
      - version: "1.0"
        type: "AlexNet"
        basic_info:
          input_size: 256
          num_classes: 14
          pretrained: false
          total_conv_layers: 1
          image_channels: 1
          total_fc_layers: 2
          total_layers: 3
          total_parameters: 6,225
          total_trainable_parameters: 6,225
          total_non_trainable_parameters: 0
          total_model_size: 0.32 MB
          
      - version: "1.1"
        type: "AlexNet"
        basic_info:
          input_size: 236
          num_classes: 4
          pretrained: false
          total_conv_layers: ? 
          total_fc_layers: ?
          total_layers: ?
          total_parameters: ?
          total_trainable_parameters: ?
          total_non_trainable_parameters: ?